### ISSUE TITLE
autocompletion causes repl to hang

### ISSUE THREAD

**Issue by artenator** [abicky/nodejs-repl.el#28]
Emacs 26.3
`nodejs-repl` v0.2.2
Nodejs version v13.5.0

To reproduce, type: "Obj" and press `TAB`, which causes emacs to hang. 
Pressing `Ctrl-g` unfreezes emacs.

Also, another interesting thing occurs when pressing `Enter` after this, the incorrect string gets sent to the repl.

```
> Obj
Uncaught ReferenceError: ObjectObj is not defined
    at repl:1
    at Script.runInContext (vm.js:131:20)
    at REPLServer.defaultEval (repl.js:425:29)
    at bound (domain.js:427:14)
    at REPLServer.runBound [as eval] (domain.js:440:12)
    at REPLServer.onLine (repl.js:750:10)
    at REPLServer.emit (events.js:305:20)
```

Might be related to #24 ?

**Comment by abicky** [comment]
Thank you for your report.
I've released [0.2.3](https://github.com/abicky/nodejs-repl.el/releases/tag/0.2.3) which supports Node.js 13. Please try it.
